apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: 2016-02-18T18:52:05Z
  name: sensor-config
data:
  .env: |
    MONGODB_URI=mongodb://dbadmin:admin@mongo-shard-router-svc.mongo:27017/developmentdb?authSource=admin
    STH_PREFIX=sth_
    # Storage Strategy: ONE_DOCUMENT_PER_VALUE / ONE_DOCUMENT_PER_TRANSACTION
    STORAGE_STRATEGY=ONE_DOCUMENT_PER_TRANSACTION
    SECRET_TOKEN=catswillruletheworld
    GITHUB_CLIENT_ID=302d190373af9cfdbdfe
    GITHUB_CLIENT_SECRET=1b5250765bdd8b5ab23dd2d1446e9d727f1d367d
    GITHIB_CALLBACK_URL=http://localhost:4200/api/auth/github/callback

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-server
  labels:
    app: sensor-server
spec:
  replicas: 1
  selector:
    matchLabels:
      run: sensor-server
  template:
    metadata:
      labels:
        run: sensor-server
    spec:
      containers:
        - name: sensor-server
          image: fiwareaustria/iot-frontend:latest
          ports:
            - containerPort: 3000
              name: api
            - containerPort: 4200
              name: gui
          volumeMounts:
            - name: sensor-config
              mountPath: /sensors/.env
              subPath: .env

      volumes:
        - name: sensor-config
          configMap:
            # Provide the name of the ConfigMap containing the files you want
            # to add to the container
            name: sensor-config


---
kind: Service
apiVersion: v1
metadata:
  name: sensor-server
spec:
  ports:
    - port: 3000
      targetPort: 3000
      name: api
      nodePort: 32111
    - port: 4200
      targetPort: 4200
      name: gui
      nodePort: 32112
  selector:
    run: sensor-server
  type: LoadBalancer




