frontend:
  replicas: 3
  image: fiwareaustria/iot-frontend:latest
  api:
    nodePort: 32111
  gui:
    nodePort: 32112
  # mongo: mongodb://dbadmin:admin@mongo-shard-router-svc.mongo:27017/iot-frontend?authSource=admin
  mongo: mongodb://dbadmin:admin@mongo-router-svc.mongo:27017/iot-frontend?authSource=admin
